global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'indicacoes'
    metrics_path: '/actuator/prometheus'
    scheme: http
    static_configs:
      - targets: ['indicacoes.railway.internal:8080']