global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:9090']

  - job_name: 'indicacoes'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['indicacoes-dev.up.railway.app']